In [1]:
import numpy as np

## Q1: Fun with arrays

**A.**  Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.


**B.** Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [4]:
# A
std_guy = np.arange(1,16).reshape(3,5)
print(std_guy.T)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [8]:
short_guy = std_guy.T[1::2]
short_guy

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [9]:
# B
n_rows = 9 # arbitrary
n_cols = 6 # arbitrary


p = np.ones((n_rows, n_cols))
p[1:n_rows-1, 1:n_cols-1] = 0
print(p)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Q2: Histrograms

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook. You download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt (and use python to download a file!)

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [11]:
column, data = np.loadtxt('sample.txt', delimiter=' ', unpack=True)


In [14]:
hist, bin_edges = np.histogram(data)
#len(hist)
#len(bin_edges)

In [15]:
for i in range(len(hist)):
    print('Bin center: ', np.mean(bin_edges[i:i+2]), ', counts: ', hist[i])

Bin center:  -27.129262572005736 , counts:  3
Bin center:  -20.21093194037355 , counts:  4
Bin center:  -13.29260130874136 , counts:  9
Bin center:  -6.374270677109173 , counts:  22
Bin center:  0.5440599545230143 , counts:  22
Bin center:  7.462390586155202 , counts:  22
Bin center:  14.38072121778739 , counts:  9
Bin center:  21.299051849419577 , counts:  7
Bin center:  28.217382481051764 , counts:  1
Bin center:  35.135713112683945 , counts:  1
